use strict;
use warnings;
no warnings qw(redefine);

1;

# this class is AUTOGENERATED and will be AUTOMATICALLY REGENERATED
# all work done in this module will be LOST


package RAST::Job;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		owner => [ DB_OBJECT, "WebServerBackend::User", 0, undef ],
		viewable => [ DB_SCALAR, undef, 0, undef ],
		server_version => [ DB_SCALAR, undef, 0, undef ],
		active => [ DB_SCALAR, undef, 0, undef ],
		last_modified => [ DB_SCALAR, undef, 0, undef ],
		genome_bp_count => [ DB_SCALAR, undef, 0, undef ],
		created_on => [ DB_SCALAR, undef, 0, undef ],
		genome_name => [ DB_SCALAR, undef, 0, undef ],
		id => [ DB_SCALAR, undef, 1, undef ],
		genome_id => [ DB_SCALAR, undef, 0, undef ],
		type => [ DB_SCALAR, undef, 0, undef ],
		genome_contig_count => [ DB_SCALAR, undef, 0, undef ],
		job_signature => [ DB_SCALAR, undef, 0, undef ],
		project_name => [ DB_SCALAR, undef, 0, undef ],
	};
}

sub unique_indices {
     return 
		[
			[ "id" ],
			[ "genome_id" ],
			[ "job_signature" ],
		];
}

sub indices {
     return 
		[
			[ "owner" ],
			[ "viewable" ],
		];
}

1;

package RAST::Status;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		stage => [ DB_SCALAR, undef, 1, undef ],
		status => [ DB_SCALAR, undef, 1, undef ],
		job => [ DB_OBJECT, "RAST::Job", 1, undef ],
	};
}

sub unique_indices {
     return 
		[
			[ "job", "stage" ],
		];
}

sub indices {
     return 
		[
			[ "job" ],
		];
}

1;

package RAST::Import;

use DBObject;
use base qw(DBObject);

sub attributes {
     return {
		priority => [ DB_SCALAR, undef, 0, undef ],
		status => [ DB_SCALAR, undef, 0, undef ],
		action => [ DB_SCALAR, undef, 0, undef ],
		reason => [ DB_SCALAR, undef, 0, undef ],
		suggested_by => [ DB_SCALAR, undef, 0, undef ],
		replaces => [ DB_SCALAR, undef, 0, undef ],
		job => [ DB_OBJECT, "RAST::Job", 1, undef ],
	};
}

sub unique_indices {
     return 
		[
			[ "job" ],
		];
}

sub indices {
     return 
		[
			[ "suggested_by" ],
			[ "priority" ],
			[ "reason" ],
			[ "status" ],
		];
}

1;
