use strict;
use warnings;
no warnings qw(redefine);

1;

# this class is AUTOGENERATED and will be AUTOMATICALLY REGENERATED
# all work done in this module will be LOST


package WebApplicationServer::User;

use DBObject;

our @ISA = qw(DBObject);

sub attributes {
     return {
		firstName => [ DB_SCALAR ],
		rights => [ DB_ARRAY_OF_SCALARS ],
		eMail => [ DB_SCALAR ],
		organisation => [ DB_OBJECT, "WebApplicationServer::Organisation" ],
		status => [ DB_SCALAR ],
		note => [ DB_SCALAR ],
		entryDate => [ DB_SCALAR ],
		login => [ DB_SCALAR ],
		password => [ DB_SCALAR ],
		lastName => [ DB_SCALAR ],
	}
}

sub mandatory_attributes {
     return {
		eMail => 1,
	}
}

1;

package WebApplicationServer::Organisation;

use DBObject;

our @ISA = qw(DBObject);

sub attributes {
     return {
		url => [ DB_SCALAR ],
		name => [ DB_SCALAR ],
		abbreviation => [ DB_SCALAR ],
	}
}

sub mandatory_attributes {
     return {
		name => 1,
	}
}

1;

package WebApplicationServer::Session;

use DBObject;

our @ISA = qw(DBObject);

sub attributes {
     return {
		session_id => [ DB_SCALAR ],
		entries => [ DB_ARRAY_OF_OBJECTS, "WebApplicationServer::SessionItem" ],
		user => [ DB_OBJECT, "WebApplicationServer::User" ],
		creation => [ DB_SCALAR ],
	}
}

sub mandatory_attributes {
     return {
		session_id => 1,
	}
}

1;

package WebApplicationServer::SessionItem;

use DBObject;

our @ISA = qw(DBObject);

sub attributes {
     return {
		additional_info => [ DB_SCALAR ],
		page => [ DB_SCALAR ],
		timestamp => [ DB_SCALAR ],
		action => [ DB_SCALAR ],
	}
}

sub mandatory_attributes {
     return {
		timestamp => 1,
	}
}

1;

package WebApplicationServer::Project;

use DBObject;

our @ISA = qw(DBObject);

sub attributes {
     return {
		organisation => [ DB_OBJECT, "WebApplicationServer::Organisation" ],
		url => [ DB_SCALAR ],
		name => [ DB_SCALAR ],
	}
}

sub mandatory_attributes {
     return {
		name => 1,
	}
}

1;

package WebApplicationServer::Request;

use DBObject;

our @ISA = qw(DBObject);

sub attributes {
     return {
		firstName => [ DB_SCALAR ],
		eMail => [ DB_SCALAR ],
		organisation => [ DB_SCALAR ],
		lastName => [ DB_SCALAR ],
		note => [ DB_SCALAR ],
	}
}

sub mandatory_attributes {
     return {
		eMail => 1,
	}
}

1;
